### PR TITLE
function for multinomial regression robust score test

### PR DESCRIPTION
**Pull request by shirmath**
Added function and corresponding documentation for robust score test of weak and global null for multinomial regression.

### CODE REVIEW

**Review by svteichman — COMMENTED** [review]
This is really impressive and great functionality to add to `raoBust`! 

In line 27 and 28 of `null10bjective` is this assuming that the design matrix `X` doesn't include an intercept column? Or should this be added even if there is an intercept column? Currently in most `raoBust` functions data is allowed to come in the `formula` and `data` format which I think gets passed to `model.matrix` which by default includes an intercept. If these lines are adding an intercept column, maybe check first whether one already exists? 

I'm a little confused about what exactly is being tested in the marginal case. It seems like in most cases `p` covariates are allowed, however, in `get_multinom_score` the hypothesis being tested is beta_j = 0. Does this mean that a joint test is run for beta_1j = ... = beta_pj = 0? If p > 1, I wonder if this is the appropriate test or if beta_kj = 0 is the appropriate test for a user-provided k? But I could be missing something and maybe this joint test for a given category is the better test here, I'm just curious about the context in which this test would come up. I suppose that if you had a categorical covariate you may want to jointly test if the beta_j for all levels of that covariate is equal to 0. 

For the joint test over all j I'm not totally following H2 here. My understand of the H matrix in a robust score test is that it should have the number of rows equal to the number of tests being run, which here I would expect to be 1 (beta_11 = ... = beta1J-1) or even p (beta_k1 = ... = beta_k,J-1) but here there are p(J-1) rows, so one for each parameter. I could be thinking of a different formulation of the robust score test, but I could use an explanation the H2 being used here. 

Finally, I think because this is new functionality for the package and to maintain code coverage, it could be good to have tests demonstrating that these functions run without errors. Specifically, I'd recommend two tests for `get_multinom_score`, one for a marginal test and one for the joint test, to show that everything works as it should and errors aren't thrown. Some helpful examples might be in "https://github.com/statdivlab/raoBust/blob/main/tests/testthat/test-use-case.R". 

Let me know if I could clarify any of these comments, I know it's a little stream-of-consciousness!

**Comment by svteichman** [comment]
Also, from the checks it seems that the documentation R-CMD-check bot is angry about the use of "\beta_j" in the parameter descriptions, try wrapping any latex in "\eqn{\beta_j}"

**Comment by adw96** [comment]
I only glanced very quickly at this but I notice that NAMESPACE isn't changing -- should one of these functions be exported?

**Comment by svteichman** [comment]
Ignore my comments above about the score test formulation - this was my confusion about the hypotheses being tested. 

To-do before merging:
-export the `multinom` function
-add packages used to "Imports" section of "DESCRIPTION" file
-add a check in for the `X` matrix to see if there is already an intercept
-add sanity check tests (the `usethis::use_test()` function is an easy way to add a testing file) for the `multinom` function
-push all these changes and see if there are any errors or warnings coming up in the R-CMD-check

**Comment by adw96** [comment]
This is looking great, @shirmath ! Very well done! 

I've made a couple of edits in the goal of making the code more "production level". Please check them out! Some examples include every function having its own file, having some tests, etc. Happy to chat about why we do it this way if you have questions. 

TODO(AW)

- check that function titles align with their goal. eg multinom_mle_weak_null doesn't actually do optimization even though the return and title suggest it does
- check T1E rates are nominal for both global and marginal
- decide on & harmonize terminology (global vs joint vs strong, weak vs marginal)
- look into NA/Inf issues and try to stabilize estimation for large scale deployment
- rename everything to be either multinomial or Poisson, as now we do both 🥳 

@shirmath I know you have other things going on this week so I'll work on the above and circle back with questions. Please do take a look at how I restructured the code, though!

@svteichman I'll let you know when it's ready for your next review (ETA next week when you're back; obviously ignore while you are travelling 👍 )

**Comment by adw96** [comment]
Hi @shirmath! 

First off, this is a great start. A few high-level comments for future

- It's good to return parameter estimates as well as test statistics. Including p-values helps a user more easily get results (I've added some of these)
- Writing modular code is good for lots of reasons. Any code that gets reused should be a function (not nec. exported)
- Unit tests help ensure that your code does what it's supposed to (I've written some)

A few requests for you

- I think that estimation under the weak null often fails. If this doesn't work, the test isn't reliable, so we need to shore this up. I don't think that it should be this unstable, even with optim. Could you please improve this aspect of the code? I would love for you to take the initiate on how to do this, but some places to get started include adding some checks that the optimization routine converges to a minimum, confirming that the estimate doesn't diverge, implementing Fisher scoring (if you can't get off-the-shelf optimizers to work), and adding some tests that show consistency of the estimate (the T1E tests could be adapted to investigate consistency). 
- Could you please modularize your code? For example, here's one place where a this chunk gets used multiple times, and could be a function eg called `matrix_to_vector`. 

```
  beta <- matrix(rep(0, (p+1)*(J-1)), ncol = J-1) #initialize full (p+1) x (J-1) beta matrix
  for (k in 1:(J-1)) {
    if (k < j) {
      beta[ ,k] <- beta_as_vector[((k-1)*(p+1)+1):(k*(p+1))]
    } else if (k == j) {
      beta[,k] <- c(beta_as_vector[(p+1)*(J-2)+1], beta_j_null)
    } else if (k > j) {
      beta[ ,k] <- beta_as_vector[((k-2)*(p+1)+1):((k-1)*(p+1))]
    }
  }
```

- Could you please add functionality for the MLE at the alternative to be returned, too?
- As you go through, if you see anything that could be more clear (eg for future maintainers), please go ahead and improve it. (We want people to use this code!) 

I'd be grateful if you could prioritize this so we can pass it along to our collaborators ASAP. 

Both @svteichman and I can answer questions.

**Comment by shirmath** [comment]
Hi @adw96. Thank you for your comments and feedback!

With regards to specific requests, I have one question I want to clarify with regards to the modularity piece, in particular the current `vector_to_matrix` function.

For implementing the `matrix_to_vector` and `vector_to_matrix` functions for modularizing the code, what is the meaning of the `null_J` parameter? Is this specifying which j we want to set as 0? What is the desired behavior if `null_J = NULL`? 
I'll implement these functions accordingly.

I should be able to implement that and functionality for returning the MLE at the alternative (unless there are also convergence issues here from off-the-shelf methods) by the end of tomorrow.

I'll also start working on investigating the issues with `nlm` and see how to reliably get an estimate of the beta parameter under the null constraint, but I'm not sure how long this will take so I can't provide a precise timeline at the moment, but this will be on the top of my priorities.

**Comment by adw96** [comment]
Thank you so much @shirmath ! 

Great questions, too. Yes, I was thinking of `null_J` as the column corresponding to the $beta_j$ such that $beta_j=0$ under the null. I totally agree with you that it doesn't make sense to set a default (as in `null_J = NULL`). This was left in there as I was drafting it and then ditching it when I ran out of time 😊 

Just FYI, I don't have a clear vision about how to best implement `matrix_to_vector` and its inverse, but I was thinking something along the lines of how you can just turn a matrix into a vector using `c()` i.e., 
```
matrix(c(1:25), nrow = 5) %>% c
```
but because $beta_j$ is fixed for $H_0: beta_j = 0$, it's length p shorter than the J*(p+1) vector that you'd get out of just calling `c()`. I think the hard part is both getting the indices right (both for which elements of the matrix to drop AND how to insert the zero-except-for-one element) AND having it be easy-to-read.

Btw, can we please have beta be (p+1)*(J-1), with the first row being the taxon-specific intercepts? `radEmu` has a p*J-dimensional beta, and being consistent will help us with forward maintenance (I always think of beta_{kj} rather than beta_{jk}). (I'm sorry -- I recognize this is tedious!)

**Comment by adw96** [comment]
Hi @svteichman !! Shirley has done a ton of work on this, and is now headed off to sunny California for the summer. I'm hoping you can take over this pull request. 

I think the best next step would be for you to review, make any changes that you think are needed, and merge this PR, and from there we can talk about some of the other things that could happen to make multinomial raoBust user-ready. 

Would you mind checking/implementing the following before merging this PR:

- writing/running some tests that theta-hat-alternative and theta-hat-null are the correct optima under their respective objective functions
- implementing some basic checks that the inputs are sensible (nrow(X) == nrow(Y), anything else you think we should check, etc)
- confirm the test controls T1E in settings where it should, doesn't in settings where it shouldn't, and has power that increases with sample size and effect size (these tests don't have to be run every time -- they could be commented out for use only when we make changes to optimization/testing)
- documentation that makes sense (Shirley wrote some and it seems good, but I think it's worth checking that it makes sense to someone else!)

?

I'll open these as an issue/enhancement, but wanted to list them here:

- Firth penalty! If having some of the algebra from @shirmath would be helpful for implementing this, let me know -- I might have what you need, or Shirley may be able to send you some relevant notes
- restructuring the repo so that there is a consistent interface, with a "family" option, for which the user can specify "poisson" or "multinomial". (for this reason)
- a vignette! 
- (less urgent) generic `H` matrix. We have `H1` and `H2` for weak and strong nulls, but this could actually be more general

Happy to discuss, too!

**Pull request merged**
